# Generated by Django 4.2.6 on 2023-11-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_teaching", "0006_persontocourse"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PersonToCourse",
            new_name="PersonCourse",
        ),
    ]
