# Generated by Django 4.2.6 on 2023-11-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_teaching", "0008_remove_personcourse_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="position",
            field=models.CharField(
                choices=[
                    ("P1", "P1"),
                    ("F1", "F1"),
                    ("UL", "UL"),
                    ("P2", "P2"),
                    ("F2", "F2"),
                    ("L", "L"),
                    ("Ext", "Ext"),
                ],
                max_length=50,
            ),
        ),
    ]
